# Generated by Django 2.1.5 on 2019-02-08 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Dept',
            new_name='dept',
        ),
    ]
